name: sc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"  # Adjusted SDK version for better compatibility

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.47
  webrtc_interface: ^1.2.0
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.1.1
  http: ^0.13.6  # Updated version for better stability

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
